resources:
  - grpc-gateway/configmap.yaml
  - grpc-gateway/deployment.yaml
#  - grpc-gateway/rollout.yaml
  - grpc-gateway/service.yaml
  - grpc-server/configmap.yaml
  - grpc-server/deployment.yaml
#  - grpc-server/rollout.yaml
  - grpc-server/service.yaml
